spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        #MySQL??
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://fxmaoyuzzz.mysql.rds.aliyuncs.com:3306/mall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root_1234
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
    application:
        name: mall-ware
    jackson:
        date-format: yyyy-mm-dd HH:mm:ss

server:
    port: 11000

logging:
    level:
        com.moyu: debug