spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        #MySQL??
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://fxmaoyuzzz.mysql.rds.aliyuncs.com:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root_1234
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
        alicloud:
            access-key: LTAI5tBk4iZ1MLp8nqG7nFMG
            secret-key: 45KVhMWQfsV7PpG8qQj4Xma5LLKwcq
            oss:
                endpoint: oss-cn-shanghai.aliyuncs.com
    application:
        name: mall-product
    jackson:
        date-format: yyyy-mm-dd HH:mm:ss
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html


server:
    port: 7001



mybatis-plus:
    global-config:
        db-config:
            id-type: AUTO
            logic-delete-value: 1
            logic-not-delete-value: 0
logging:
    level:
        com.moyu.mall: debug

